### ISSUE TITLE
Error code: 1011 Error reason: leveldb: not found

### ISSUE THREAD

**Issue by andrewklau** [vechain/thor#154]
Subscribing to the transfers websocket using thorify will error out with `Error: Connection closed. Error code: 1011 Error reason: leveldb: not found`

## OS Version: 
Docker image: vechain/thor:latest
Docker Image ID: 41e3c323a81f
Thor version 1.0.2-41b0c69-release

## Expected behavior

Receive transfers stream

## Actual behavior

```
node app.js 
{ number: 826337,
  id: '0x000c9be1a96e7960a75606385daac62eaca9ee6b5e4a8ae10022cd77833dc455',
  size: 239,
  parentID: '0x000c9be03d88435ade9c38f8844948c5dad7a83cb8c97c383250ae1f430a08db',
  timestamp: 1538282050,
  gasLimit: 14321460,
  beneficiary: '0xb4094c25f86d628fdd571afc4077f0d0196afb48',
  gasUsed: 0,
  totalScore: 2522048,
  txsRoot: '0x45b0cfc220ceec5b7c1c62c4d4193d38e4eba48e8815729ce75f9c0ab0e4c1c0',
  stateRoot: '0xb76e493f37d4c0f5fae869746b09b4238a17ce23dc497296a125b6d5b49cfea6',
  receiptsRoot: '0x45b0cfc220ceec5b7c1c62c4d4193d38e4eba48e8815729ce75f9c0ab0e4c1c0',
  signer: '0xab7b27fc9e7d29f9f2e5bd361747a5515d0cc2d1',
  isTrunk: true,
  transactions: [] }
Error: Connection closed. Error code: 1011 Error reason: leveldb: not found
    at WebSocket.ws.onclose (//services/thorify/node_modules/thorify/dist/provider/index.js:114:56)
    at WebSocket.onClose (//services/thorify/node_modules/ws/lib/event-target.js:124:16)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (//services/thorify/node_modules/ws/lib/websocket.js:172:10)
    at Socket.socketOnClose (//services/thorify/node_modules/ws/lib/websocket.js:780:15)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12)
```

## Steps to reproduce the behavior

- Start node with docker
- Subscribe to transfers using thorify

**Comment by andrewklau** [comment]
The issue is fixed in master, so will wait for the next docker image release.

Thanks
